uploads = []
generated = []

[[outputs]]
id = "GPuw_OHjAF6bAl8ydKNJV"
uri = "file://pinnacle-production.zip"
type = "unspecified"
title = "Pinnacle Production Package (pre-built, no build required)"

[[outputs]]
id = "e_xhdcNftx5WMdpEsho8k"
uri = "file://pinnacle-production-package.zip"
type = "unspecified"
title = "Pinnacle Academic Classes — Production Package (14.3 MB)"

[[outputs]]
id = "KRZnxGhiTfR3Fquz04ozz"
uri = "file://pinnacle-prebuilt-docker.zip"
type = "unspecified"
title = "Version 1: Pre-built (Run instantly — no build needed) — 14.3 MB"

[[outputs]]
id = "E0D2ZkzfYAsbHWEXCZEYj"
uri = "file://pinnacle-build-from-source.zip"
type = "unspecified"
title = "Version 2: Build from Source (Full source + mobile app) — 17.9 MB"

[[outputs]]
id = "QG4Hpl5wgewfVPgxZWhlj"
uri = "file://releases/pinnacle-dist-2026-05-13.zip"
type = "unspecified"
title = "Pinnacle — Pre-built Production Bundle (dist, 22 MB)"

[[outputs]]
id = "4I-VqCpARzxBBj2QgBacK"
uri = "file://releases/pinnacle-source-2026-05-13.zip"
type = "unspecified"
title = "Pinnacle — Full Source Archive (103 MB)"

[[outputs]]
id = "kT-dp9NcAc83BFEjQmvnR"
uri = "file://releases/pinnacle-source-2026-05-14.zip"
type = "unspecified"
title = "Pinnacle — Source (2026-05-14)"

[[outputs]]
id = "5rucGopxUIBfWTrHlXImV"
uri = "file://releases/pinnacle-dist-2026-05-14.zip"
type = "unspecified"
title = "Pinnacle — Dist / built artifacts (2026-05-14)"
