import { drizzle } from "drizzle-orm/node-postgres";
import { Pool } from "pg";
import { questionBank } from "./schema/index";

const pool = new Pool({ connectionString: process.env.DATABASE_URL! });
const db = drizzle(pool);

interface SeedQuestion {
  subject: string;
  topic: string;
  classGrade: string;
  year: number | null;
  difficulty: "easy" | "medium" | "hard";
  questionType: "mcq";
  questionText: string;
  options: { A: string; B: string; C: string; D: string };
  correctAnswer: string;
  solution: string;
  marks: number;
}

const physics: SeedQuestion[] = [
  { subject: "Physics", topic: "Mechanics", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "A body of mass 5 kg is moving with a velocity of 10 m/s. What is its kinetic energy?", options: { A: "250 J", B: "500 J", C: "100 J", D: "50 J" }, correctAnswer: "A", solution: "Kinetic energy = ½mv² = ½ × 5 × 10² = ½ × 5 × 100 = 250 J.", marks: 4 },
  { subject: "Physics", topic: "Mechanics", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "Newton's first law of motion is also known as the law of:", options: { A: "Acceleration", B: "Inertia", C: "Action-reaction", D: "Gravitation" }, correctAnswer: "B", solution: "Newton's first law states that a body at rest stays at rest and a body in motion stays in uniform motion unless acted upon by an external force. This property is called inertia.", marks: 4 },
  { subject: "Physics", topic: "Mechanics", classGrade: "11", year: 2023, difficulty: "medium", questionType: "mcq", questionText: "A projectile is fired at an angle of 30° with the horizontal with a speed of 20 m/s. What is the maximum height reached? (g = 10 m/s²)", options: { A: "5 m", B: "10 m", C: "15 m", D: "20 m" }, correctAnswer: "A", solution: "Maximum height H = u²sin²θ / (2g) = (20)² × sin²30° / (2 × 10) = 400 × 0.25 / 20 = 5 m.", marks: 4 },
  { subject: "Physics", topic: "Mechanics", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "Two blocks of masses 2 kg and 3 kg are connected by a light string passing over a frictionless pulley (Atwood machine). What is the acceleration of the system? (g = 10 m/s²)", options: { A: "2 m/s²", B: "4 m/s²", C: "5 m/s²", D: "6 m/s²" }, correctAnswer: "A", solution: "For an Atwood machine, a = (m₂ - m₁)g / (m₁ + m₂) = (3 - 2) × 10 / (2 + 3) = 10/5 = 2 m/s².", marks: 4 },
  { subject: "Physics", topic: "Mechanics", classGrade: "11", year: null, difficulty: "hard", questionType: "mcq", questionText: "A block slides down a rough inclined plane of angle 45° with a constant velocity. What is the coefficient of kinetic friction?", options: { A: "0.5", B: "0.707", C: "1.0", D: "1.414" }, correctAnswer: "C", solution: "At constant velocity, net force = 0. mg sin45° = μk mg cos45°. Therefore μk = tan45° = 1.0.", marks: 4 },
  { subject: "Physics", topic: "Mechanics", classGrade: "12", year: 2022, difficulty: "medium", questionType: "mcq", questionText: "The moment of inertia of a uniform circular disc of mass M and radius R about an axis passing through its centre and perpendicular to its plane is:", options: { A: "MR²", B: "½MR²", C: "¼MR²", D: "⅔MR²" }, correctAnswer: "B", solution: "For a uniform disc about its central axis perpendicular to the plane, I = ½MR². This is a standard result derived from integration.", marks: 4 },
  { subject: "Physics", topic: "Mechanics", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "A car accelerates uniformly from rest to 20 m/s in 10 seconds. What distance does it cover?", options: { A: "50 m", B: "100 m", C: "200 m", D: "400 m" }, correctAnswer: "B", solution: "Using s = ut + ½at², where u = 0, a = 20/10 = 2 m/s². s = 0 + ½ × 2 × 100 = 100 m.", marks: 4 },
  { subject: "Physics", topic: "Thermodynamics", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "In an isothermal process, which quantity remains constant?", options: { A: "Pressure", B: "Volume", C: "Temperature", D: "Entropy" }, correctAnswer: "C", solution: "Isothermal means 'equal temperature'. In an isothermal process, the temperature of the system remains constant throughout the process.", marks: 4 },
  { subject: "Physics", topic: "Thermodynamics", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "An ideal gas undergoes an adiabatic expansion. Which statement is correct?", options: { A: "Temperature increases", B: "Temperature decreases", C: "Temperature stays constant", D: "Internal energy increases" }, correctAnswer: "B", solution: "In adiabatic expansion, no heat is exchanged with surroundings (Q = 0). Work is done by the gas at the expense of internal energy, so temperature decreases.", marks: 4 },
  { subject: "Physics", topic: "Thermodynamics", classGrade: "11", year: 2021, difficulty: "hard", questionType: "mcq", questionText: "A Carnot engine operates between temperatures 600 K and 300 K. If it absorbs 1000 J of heat from the source, what is the work done by the engine?", options: { A: "250 J", B: "500 J", C: "750 J", D: "1000 J" }, correctAnswer: "B", solution: "Efficiency of Carnot engine η = 1 - T₂/T₁ = 1 - 300/600 = 0.5. Work done W = η × Q₁ = 0.5 × 1000 = 500 J.", marks: 4 },
  { subject: "Physics", topic: "Optics", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The phenomenon of splitting of white light into its constituent colours by a prism is called:", options: { A: "Reflection", B: "Refraction", C: "Dispersion", D: "Diffraction" }, correctAnswer: "C", solution: "Dispersion is the phenomenon of splitting of white light into its seven constituent colours (VIBGYOR) when passed through a prism, due to different wavelengths having different refractive indices.", marks: 4 },
  { subject: "Physics", topic: "Optics", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "A convex lens of focal length 20 cm forms a real image at 60 cm from the lens. What is the object distance?", options: { A: "15 cm", B: "20 cm", C: "30 cm", D: "40 cm" }, correctAnswer: "C", solution: "Using lens formula 1/v - 1/u = 1/f. Here v = +60 cm, f = +20 cm. 1/u = 1/v - 1/f = 1/60 - 1/20 = (1-3)/60 = -2/60 = -1/30. So u = -30 cm. Object distance = 30 cm.", marks: 4 },
  { subject: "Physics", topic: "Optics", classGrade: "12", year: 2023, difficulty: "hard", questionType: "mcq", questionText: "In Young's double-slit experiment, the fringe width is 0.5 mm. If the wavelength of light used is doubled while keeping other parameters same, the new fringe width will be:", options: { A: "0.25 mm", B: "0.5 mm", C: "1.0 mm", D: "2.0 mm" }, correctAnswer: "C", solution: "Fringe width β = λD/d. If wavelength λ is doubled, β' = 2λD/d = 2β = 2 × 0.5 = 1.0 mm.", marks: 4 },
  { subject: "Physics", topic: "Electrostatics", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "Two point charges of +2 μC and -2 μC are placed 10 cm apart. The system is called:", options: { A: "Monopole", B: "Dipole", C: "Quadrupole", D: "Neutral charge" }, correctAnswer: "B", solution: "Two equal and opposite charges separated by a small distance form an electric dipole. Here +2 μC and -2 μC separated by 10 cm constitute a dipole.", marks: 4 },
  { subject: "Physics", topic: "Electrostatics", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "The electric field at a distance r from an infinitely long uniformly charged wire with linear charge density λ is:", options: { A: "λ/(2πε₀r)", B: "λ/(4πε₀r²)", C: "λ/(2πε₀r²)", D: "λ/(4πε₀r)" }, correctAnswer: "A", solution: "Using Gauss's law with a cylindrical Gaussian surface: E × 2πrL = λL/ε₀. Therefore E = λ/(2πε₀r).", marks: 4 },
  { subject: "Physics", topic: "Electrostatics", classGrade: "12", year: 2022, difficulty: "hard", questionType: "mcq", questionText: "Three identical capacitors each of capacitance C are connected first in series and then in parallel. The ratio of equivalent capacitance in series to parallel is:", options: { A: "1:9", B: "1:3", C: "3:1", D: "9:1" }, correctAnswer: "A", solution: "In series: 1/Cs = 1/C + 1/C + 1/C = 3/C, so Cs = C/3. In parallel: Cp = C + C + C = 3C. Ratio = Cs/Cp = (C/3)/(3C) = 1/9.", marks: 4 },
  { subject: "Physics", topic: "Magnetism", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The SI unit of magnetic flux is:", options: { A: "Tesla", B: "Weber", C: "Henry", D: "Gauss" }, correctAnswer: "B", solution: "Magnetic flux Φ = B·A, where B is magnetic field (Tesla) and A is area (m²). The SI unit of magnetic flux is Weber (Wb) = T·m².", marks: 4 },
  { subject: "Physics", topic: "Magnetism", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "A circular loop of radius 0.1 m carries a current of 5 A. What is the magnetic field at its centre? (μ₀ = 4π × 10⁻⁷ T·m/A)", options: { A: "π × 10⁻⁵ T", B: "2π × 10⁻⁵ T", C: "3π × 10⁻⁵ T", D: "4π × 10⁻⁵ T" }, correctAnswer: "A", solution: "B at centre of circular loop = μ₀I/(2R) = (4π × 10⁻⁷ × 5)/(2 × 0.1) = 20π × 10⁻⁷ / 0.2 = π × 10⁻⁵ T.", marks: 4 },
  { subject: "Physics", topic: "Magnetism", classGrade: "12", year: 2021, difficulty: "hard", questionType: "mcq", questionText: "A charged particle enters a uniform magnetic field perpendicular to the field with speed v. If the charge is doubled and speed is halved, the radius of the circular path:", options: { A: "Remains same", B: "Doubles", C: "Halves", D: "Becomes one-fourth" }, correctAnswer: "D", solution: "Radius r = mv/(qB). New radius r' = m(v/2)/(2qB) = mv/(4qB) = r/4. The radius becomes one-fourth.", marks: 4 },
  { subject: "Physics", topic: "Modern Physics", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The photoelectric effect demonstrates the:", options: { A: "Wave nature of light", B: "Particle nature of light", C: "Dual nature of matter", D: "Wave nature of electrons" }, correctAnswer: "B", solution: "The photoelectric effect, explained by Einstein, demonstrates that light consists of discrete packets of energy called photons, thus showing the particle nature of light.", marks: 4 },
  { subject: "Physics", topic: "Modern Physics", classGrade: "12", year: 2023, difficulty: "medium", questionType: "mcq", questionText: "The work function of a metal is 4.0 eV. What is the threshold wavelength for the photoelectric effect? (hc = 12400 eV·Å)", options: { A: "3100 Å", B: "4000 Å", C: "5000 Å", D: "6200 Å" }, correctAnswer: "A", solution: "Threshold wavelength λ₀ = hc/φ = 12400/4.0 = 3100 Å.", marks: 4 },
  { subject: "Physics", topic: "Modern Physics", classGrade: "12", year: null, difficulty: "hard", questionType: "mcq", questionText: "In a hydrogen atom, the ratio of the radii of the 3rd orbit to the 1st orbit is:", options: { A: "3:1", B: "9:1", C: "1:3", D: "1:9" }, correctAnswer: "B", solution: "Bohr radius rₙ = n²a₀ where a₀ is the Bohr radius. r₃/r₁ = 3²/1² = 9/1 = 9:1.", marks: 4 },
  { subject: "Physics", topic: "Waves", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The speed of sound in air at 20°C is approximately:", options: { A: "230 m/s", B: "343 m/s", C: "500 m/s", D: "700 m/s" }, correctAnswer: "B", solution: "The speed of sound in air at 20°C (room temperature) is approximately 343 m/s. It increases by about 0.6 m/s for each degree Celsius rise in temperature.", marks: 4 },
  { subject: "Physics", topic: "Waves", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "A tuning fork of frequency 256 Hz produces 4 beats per second with another tuning fork. The frequency of the second fork could be:", options: { A: "250 Hz or 262 Hz", B: "252 Hz or 260 Hz", C: "254 Hz or 258 Hz", D: "248 Hz or 264 Hz" }, correctAnswer: "B", solution: "Beat frequency = |f₁ - f₂|. So |256 - f₂| = 4, giving f₂ = 256 + 4 = 260 Hz or f₂ = 256 - 4 = 252 Hz.", marks: 4 },
  { subject: "Physics", topic: "Waves", classGrade: "11", year: 2022, difficulty: "hard", questionType: "mcq", questionText: "A string of length 1 m and mass 0.1 kg is under a tension of 40 N. What is the fundamental frequency of vibration?", options: { A: "10 Hz", B: "20 Hz", C: "50 Hz", D: "100 Hz" }, correctAnswer: "A", solution: "Linear mass density μ = mass/length = 0.1/1 = 0.1 kg/m. Wave speed v = √(T/μ) = √(40/0.1) = √400 = 20 m/s. Fundamental frequency f₁ = v/(2L) = 20/(2 × 1) = 10 Hz.", marks: 4 },
  { subject: "Physics", topic: "Gravitation", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The escape velocity from Earth's surface is approximately:", options: { A: "7.9 km/s", B: "11.2 km/s", C: "15.0 km/s", D: "3.1 km/s" }, correctAnswer: "B", solution: "The escape velocity from Earth's surface is approximately 11.2 km/s. It is given by vₑ = √(2gR) where g = 9.8 m/s² and R is Earth's radius.", marks: 4 },
  { subject: "Physics", topic: "Gravitation", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "If the radius of Earth were doubled keeping its mass the same, the value of acceleration due to gravity on the surface would become:", options: { A: "g/4", B: "g/2", C: "2g", D: "4g" }, correctAnswer: "A", solution: "g = GM/R². If R becomes 2R, g' = GM/(2R)² = GM/(4R²) = g/4. Gravity would become one-fourth.", marks: 4 },
  { subject: "Physics", topic: "Current Electricity", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The resistance of a wire is directly proportional to its:", options: { A: "Cross-sectional area", B: "Length", C: "Temperature coefficient", D: "Current flowing through it" }, correctAnswer: "B", solution: "Resistance R = ρL/A, where ρ is resistivity, L is length, and A is cross-sectional area. R is directly proportional to length L.", marks: 4 },
  { subject: "Physics", topic: "Current Electricity", classGrade: "12", year: 2023, difficulty: "medium", questionType: "mcq", questionText: "In a Wheatstone bridge, the four resistances are P = 10 Ω, Q = 20 Ω, R = 15 Ω, and S = 30 Ω. The bridge is:", options: { A: "Balanced", B: "Unbalanced with current left to right", C: "Unbalanced with current right to left", D: "Cannot be determined" }, correctAnswer: "A", solution: "For a balanced Wheatstone bridge, P/Q = R/S. Here P/Q = 10/20 = 0.5 and R/S = 15/30 = 0.5. Since P/Q = R/S, the bridge is balanced.", marks: 4 },
  { subject: "Physics", topic: "Current Electricity", classGrade: "12", year: null, difficulty: "hard", questionType: "mcq", questionText: "Five identical resistors, each of 1 Ω, are connected to form a bridge circuit. One resistor is in the galvanometer arm. What is the effective resistance between the two supply terminals?", options: { A: "0.5 Ω", B: "1.0 Ω", C: "1.5 Ω", D: "2.0 Ω" }, correctAnswer: "B", solution: "In a balanced Wheatstone bridge with all equal resistances (1 Ω each), no current flows through the galvanometer arm. The circuit reduces to two parallel paths, each with two 1 Ω in series: (2 × 2)/(2 + 2) = 1 Ω.", marks: 4 },
  { subject: "Physics", topic: "Electromagnetic Induction", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "Lenz's law is a consequence of the law of conservation of:", options: { A: "Charge", B: "Momentum", C: "Energy", D: "Mass" }, correctAnswer: "C", solution: "Lenz's law states that the direction of induced EMF opposes the change causing it. This is a consequence of the conservation of energy — the induced current does work against the changing flux.", marks: 4 },
  { subject: "Physics", topic: "Electromagnetic Induction", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "A coil of 100 turns has a flux of 0.02 Wb through it. If the flux decreases to zero in 0.01 s, the induced EMF is:", options: { A: "2 V", B: "20 V", C: "200 V", D: "2000 V" }, correctAnswer: "C", solution: "EMF = -N × dΦ/dt = -100 × (0 - 0.02)/0.01 = -100 × (-2) = 200 V.", marks: 4 },
  { subject: "Physics", topic: "Semiconductor", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "In a p-n junction diode, the depletion region contains:", options: { A: "Free electrons only", B: "Holes only", C: "Immobile ions", D: "Mobile charge carriers" }, correctAnswer: "C", solution: "The depletion region is formed at the p-n junction where mobile charge carriers (electrons and holes) have diffused and recombined, leaving behind immobile positive donor ions on the n-side and negative acceptor ions on the p-side.", marks: 4 },
  { subject: "Physics", topic: "Semiconductor", classGrade: "12", year: 2022, difficulty: "medium", questionType: "mcq", questionText: "A full-wave rectifier uses a centre-tapped transformer. If the input frequency is 50 Hz, the output ripple frequency is:", options: { A: "25 Hz", B: "50 Hz", C: "100 Hz", D: "200 Hz" }, correctAnswer: "C", solution: "In a full-wave rectifier, both halves of the input cycle are rectified, so the output frequency is twice the input frequency: 2 × 50 = 100 Hz.", marks: 4 },
  { subject: "Physics", topic: "Semiconductor", classGrade: "12", year: null, difficulty: "hard", questionType: "mcq", questionText: "In a transistor, the base region is:", options: { A: "Thick and heavily doped", B: "Thin and lightly doped", C: "Thick and lightly doped", D: "Thin and heavily doped" }, correctAnswer: "B", solution: "The base region of a transistor is intentionally made very thin and lightly doped so that most of the charge carriers injected from the emitter pass through to the collector, giving high current gain.", marks: 4 },
  { subject: "Physics", topic: "Units and Measurement", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The dimensional formula of pressure is:", options: { A: "[ML⁻¹T⁻²]", B: "[MLT⁻²]", C: "[ML²T⁻²]", D: "[ML⁻²T⁻²]" }, correctAnswer: "A", solution: "Pressure = Force/Area = [MLT⁻²]/[L²] = [ML⁻¹T⁻²].", marks: 4 },
  { subject: "Physics", topic: "Units and Measurement", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "If the percentage errors in measurement of length and time are 1% and 2% respectively, the percentage error in the measurement of velocity is:", options: { A: "1%", B: "2%", C: "3%", D: "4%" }, correctAnswer: "C", solution: "Velocity = Length/Time. Percentage error in velocity = % error in length + % error in time = 1% + 2% = 3%.", marks: 4 },
  { subject: "Physics", topic: "Fluid Mechanics", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "Bernoulli's principle is essentially a statement of conservation of:", options: { A: "Mass", B: "Momentum", C: "Energy", D: "Angular momentum" }, correctAnswer: "C", solution: "Bernoulli's equation relates pressure energy, kinetic energy, and potential energy per unit volume of a flowing fluid. It is a statement of conservation of energy for fluid flow.", marks: 4 },
  { subject: "Physics", topic: "Fluid Mechanics", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "A hydraulic lift has pistons of cross-sectional area 1 cm² and 100 cm². A force of 10 N is applied on the smaller piston. The force on the larger piston is:", options: { A: "100 N", B: "1000 N", C: "10 N", D: "10000 N" }, correctAnswer: "B", solution: "By Pascal's law: F₁/A₁ = F₂/A₂. F₂ = F₁ × A₂/A₁ = 10 × 100/1 = 1000 N.", marks: 4 },
  { subject: "Physics", topic: "Rotational Motion", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "A disc and a ring of equal mass and radius roll down an incline without slipping. Which reaches the bottom first?", options: { A: "Disc", B: "Ring", C: "Both together", D: "Depends on the angle" }, correctAnswer: "A", solution: "For rolling without slipping, acceleration a = g sinθ / (1 + I/MR²). For disc I = ½MR², so a = g sinθ/(3/2). For ring I = MR², so a = g sinθ/2. The disc has greater acceleration and reaches first.", marks: 4 },
  { subject: "Physics", topic: "Oscillations", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The time period of a simple pendulum depends on:", options: { A: "Mass of the bob", B: "Amplitude of oscillation", C: "Length and gravitational acceleration", D: "Material of the string" }, correctAnswer: "C", solution: "Time period of a simple pendulum T = 2π√(L/g). It depends only on the length L of the pendulum and the acceleration due to gravity g, not on mass or amplitude (for small oscillations).", marks: 4 },
  { subject: "Physics", topic: "Oscillations", classGrade: "11", year: 2021, difficulty: "medium", questionType: "mcq", questionText: "A mass-spring system has a spring constant of 200 N/m and a mass of 0.5 kg. What is the frequency of oscillation?", options: { A: "1/(π) Hz", B: "10/π Hz", C: "π/10 Hz", D: "20/π Hz" }, correctAnswer: "B", solution: "Frequency f = (1/2π)√(k/m) = (1/2π)√(200/0.5) = (1/2π)√400 = 20/(2π) = 10/π Hz.", marks: 4 },
  { subject: "Physics", topic: "Dual Nature of Matter", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "The de Broglie wavelength of an electron accelerated through a potential difference of 100 V is approximately:", options: { A: "0.123 nm", B: "1.23 nm", C: "12.3 nm", D: "0.0123 nm" }, correctAnswer: "A", solution: "λ = 1.226/√V nm = 1.226/√100 = 1.226/10 = 0.1226 ≈ 0.123 nm.", marks: 4 },
  { subject: "Physics", topic: "Nuclear Physics", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The number of neutrons in the nucleus of ²³⁸U₉₂ is:", options: { A: "92", B: "146", C: "238", D: "330" }, correctAnswer: "B", solution: "Number of neutrons = Mass number - Atomic number = 238 - 92 = 146.", marks: 4 },
  { subject: "Physics", topic: "Nuclear Physics", classGrade: "12", year: 2023, difficulty: "medium", questionType: "mcq", questionText: "The half-life of a radioactive substance is 20 minutes. What fraction of the original sample remains after 1 hour?", options: { A: "1/2", B: "1/4", C: "1/8", D: "1/16" }, correctAnswer: "C", solution: "Number of half-lives = 60/20 = 3. Fraction remaining = (1/2)³ = 1/8.", marks: 4 },
  { subject: "Physics", topic: "Communication Systems", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The process of superimposing a low-frequency signal on a high-frequency carrier wave is called:", options: { A: "Demodulation", B: "Modulation", C: "Amplification", D: "Rectification" }, correctAnswer: "B", solution: "Modulation is the process of varying some property (amplitude, frequency, or phase) of a high-frequency carrier wave in accordance with the low-frequency message signal.", marks: 4 },
  { subject: "Physics", topic: "Electromagnetic Waves", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "Which electromagnetic wave has the highest frequency?", options: { A: "Radio waves", B: "Microwaves", C: "X-rays", D: "Gamma rays" }, correctAnswer: "D", solution: "In the electromagnetic spectrum, gamma rays have the highest frequency (and shortest wavelength). The order from lowest to highest frequency: Radio < Microwave < Infrared < Visible < UV < X-rays < Gamma rays.", marks: 4 },
  { subject: "Physics", topic: "Alternating Current", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "In an LCR series circuit at resonance, the impedance is:", options: { A: "Maximum", B: "Zero", C: "Equal to resistance R", D: "Equal to inductance XL" }, correctAnswer: "C", solution: "At resonance, XL = XC, so they cancel out. Impedance Z = √(R² + (XL - XC)²) = √(R²) = R. The impedance equals the resistance.", marks: 4 },
  { subject: "Physics", topic: "Mechanics", classGrade: "12", year: 2023, difficulty: "medium", questionType: "mcq", questionText: "A body is thrown vertically upward with velocity u. The maximum height reached is:", options: { A: "u²/g", B: "u²/2g", C: "2u²/g", D: "u/2g" }, correctAnswer: "B", solution: "At maximum height, v = 0. Using v² = u² - 2gH: 0 = u² - 2gH, so H = u²/(2g).", marks: 4 },
  { subject: "Physics", topic: "Work and Energy", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "Work done by a force is zero when the angle between force and displacement is:", options: { A: "0°", B: "45°", C: "90°", D: "180°" }, correctAnswer: "C", solution: "W = Fd cosθ. When θ = 90°, cos90° = 0, so W = 0.", marks: 4 },
  { subject: "Physics", topic: "Heat Transfer", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "Heat transfer by convection occurs mainly in:", options: { A: "Solids only", B: "Fluids (liquids and gases)", C: "Vacuum", D: "All states equally" }, correctAnswer: "B", solution: "Convection requires bulk movement of fluid particles. It occurs in liquids and gases.", marks: 4 },
  { subject: "Physics", topic: "Ray Optics", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "The critical angle for total internal reflection depends on:", options: { A: "Angle of incidence only", B: "Refractive indices of both media", C: "Wavelength only", D: "Temperature only" }, correctAnswer: "B", solution: "Critical angle sinθc = n₂/n₁ (where n₁ > n₂). It depends on the refractive indices of both media.", marks: 4 },
  { subject: "Physics", topic: "Electric Potential", classGrade: "12", year: 2022, difficulty: "medium", questionType: "mcq", questionText: "The electric potential at a point due to a point charge q at distance r is:", options: { A: "kq/r²", B: "kq/r", C: "kq²/r", D: "kr/q" }, correctAnswer: "B", solution: "Electric potential V = kq/r = q/(4πε₀r). Electric field E = kq/r² (inverse square), but potential is inverse r.", marks: 4 },
  { subject: "Physics", topic: "Wave Optics", classGrade: "12", year: null, difficulty: "hard", questionType: "mcq", questionText: "Resolving power of a microscope increases with:", options: { A: "Decrease in wavelength", B: "Increase in wavelength", C: "Decrease in aperture", D: "Increase in focal length" }, correctAnswer: "A", solution: "Resolving power ∝ 1/λ. Shorter wavelength gives better resolution.", marks: 4 },
  { subject: "Physics", topic: "Elasticity", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "Young's modulus is the ratio of:", options: { A: "Shear stress to shear strain", B: "Longitudinal stress to longitudinal strain", C: "Volume stress to volume strain", D: "Force to area" }, correctAnswer: "B", solution: "Young's modulus Y = Longitudinal stress / Longitudinal strain = (F/A) / (ΔL/L).", marks: 4 },
];

const chemistry: SeedQuestion[] = [
  { subject: "Chemistry", topic: "Atomic Structure", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The maximum number of electrons that can be accommodated in the 3rd shell (n=3) is:", options: { A: "2", B: "8", C: "18", D: "32" }, correctAnswer: "C", solution: "Maximum electrons in nth shell = 2n². For n=3: 2(3)² = 2 × 9 = 18.", marks: 4 },
  { subject: "Chemistry", topic: "Atomic Structure", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "Which quantum number determines the shape of an orbital?", options: { A: "Principal (n)", B: "Azimuthal (l)", C: "Magnetic (mₗ)", D: "Spin (mₛ)" }, correctAnswer: "B", solution: "The azimuthal quantum number (l) determines the shape of an orbital: l=0 (s, spherical), l=1 (p, dumbbell), l=2 (d, cloverleaf), l=3 (f, complex).", marks: 4 },
  { subject: "Chemistry", topic: "Atomic Structure", classGrade: "11", year: 2022, difficulty: "hard", questionType: "mcq", questionText: "The number of radial nodes in the 3p orbital is:", options: { A: "0", B: "1", C: "2", D: "3" }, correctAnswer: "B", solution: "Radial nodes = n - l - 1. For 3p: n=3, l=1. Radial nodes = 3 - 1 - 1 = 1.", marks: 4 },
  { subject: "Chemistry", topic: "Chemical Bonding", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The bond angle in a water molecule (H₂O) is approximately:", options: { A: "90°", B: "104.5°", C: "109.5°", D: "120°" }, correctAnswer: "B", solution: "Water has two bond pairs and two lone pairs. The lone pairs compress the bond angle from the ideal tetrahedral 109.5° to approximately 104.5°.", marks: 4 },
  { subject: "Chemistry", topic: "Chemical Bonding", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "Which of the following molecules has a zero dipole moment?", options: { A: "H₂O", B: "NH₃", C: "CO₂", D: "HCl" }, correctAnswer: "C", solution: "CO₂ is a linear molecule (O=C=O) with two equal and opposite bond dipoles that cancel each other, resulting in zero net dipole moment.", marks: 4 },
  { subject: "Chemistry", topic: "Chemical Bonding", classGrade: "11", year: null, difficulty: "hard", questionType: "mcq", questionText: "According to molecular orbital theory, the bond order of O₂ is:", options: { A: "1", B: "1.5", C: "2", D: "3" }, correctAnswer: "C", solution: "O₂ has 16 electrons. MO configuration: σ1s², σ*1s², σ2s², σ*2s², σ2p², π2p⁴, π*2p². Bond order = (10 - 6)/2 = 2.", marks: 4 },
  { subject: "Chemistry", topic: "Periodic Table", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "Elements in the same group of the periodic table have the same number of:", options: { A: "Protons", B: "Neutrons", C: "Valence electrons", D: "Total electrons" }, correctAnswer: "C", solution: "Elements in the same group have the same number of valence electrons, which gives them similar chemical properties.", marks: 4 },
  { subject: "Chemistry", topic: "Periodic Table", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "Which of the following has the smallest atomic radius?", options: { A: "Na", B: "Mg", C: "Al", D: "Si" }, correctAnswer: "D", solution: "Across a period (left to right), atomic radius decreases due to increasing nuclear charge with same number of shells. Na > Mg > Al > Si.", marks: 4 },
  { subject: "Chemistry", topic: "Periodic Table", classGrade: "11", year: 2023, difficulty: "hard", questionType: "mcq", questionText: "The element with the highest first ionisation energy among the following is:", options: { A: "Nitrogen", B: "Oxygen", C: "Fluorine", D: "Neon" }, correctAnswer: "D", solution: "Noble gases have the highest ionisation energy in their period due to completely filled, stable electron configuration. Among the options, Neon (Ne) has the highest first ionisation energy.", marks: 4 },
  { subject: "Chemistry", topic: "Thermochemistry", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "An exothermic reaction is one in which:", options: { A: "Heat is absorbed", B: "Heat is released", C: "Temperature decreases", D: "Entropy decreases" }, correctAnswer: "B", solution: "In an exothermic reaction, the system releases heat to the surroundings, so ΔH is negative. The products have lower energy than the reactants.", marks: 4 },
  { subject: "Chemistry", topic: "Thermochemistry", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "According to Hess's law, the enthalpy change for a reaction:", options: { A: "Depends on the path taken", B: "Is independent of the path taken", C: "Is always positive", D: "Is always negative" }, correctAnswer: "B", solution: "Hess's law states that the total enthalpy change for a reaction is independent of the path taken. It depends only on the initial and final states.", marks: 4 },
  { subject: "Chemistry", topic: "Equilibrium", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The pH of a 0.01 M HCl solution is:", options: { A: "1", B: "2", C: "3", D: "4" }, correctAnswer: "B", solution: "HCl is a strong acid and fully dissociates. [H⁺] = 0.01 M = 10⁻² M. pH = -log[H⁺] = -log(10⁻²) = 2.", marks: 4 },
  { subject: "Chemistry", topic: "Equilibrium", classGrade: "11", year: 2021, difficulty: "medium", questionType: "mcq", questionText: "For a reaction at equilibrium, if the concentration of products is increased, the equilibrium will:", options: { A: "Shift to the right", B: "Shift to the left", C: "Not change", D: "Oscillate" }, correctAnswer: "B", solution: "According to Le Chatelier's principle, if the concentration of products is increased, the equilibrium shifts to the left (toward reactants) to counteract the change.", marks: 4 },
  { subject: "Chemistry", topic: "Equilibrium", classGrade: "11", year: null, difficulty: "hard", questionType: "mcq", questionText: "The solubility product (Ksp) of AgCl is 1.8 × 10⁻¹⁰. The molar solubility of AgCl in pure water is:", options: { A: "1.34 × 10⁻⁵ M", B: "1.8 × 10⁻⁵ M", C: "1.34 × 10⁻¹⁰ M", D: "9.0 × 10⁻⁶ M" }, correctAnswer: "A", solution: "AgCl → Ag⁺ + Cl⁻. If solubility = s, then Ksp = s². s = √(Ksp) = √(1.8 × 10⁻¹⁰) = 1.34 × 10⁻⁵ M.", marks: 4 },
  { subject: "Chemistry", topic: "Organic Chemistry", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The IUPAC name of CH₃CH₂OH is:", options: { A: "Methanol", B: "Ethanol", C: "Propanol", D: "Butanol" }, correctAnswer: "B", solution: "CH₃CH₂OH has 2 carbon atoms with an -OH group. The parent chain is ethane, and the functional group is -ol. IUPAC name: ethanol.", marks: 4 },
  { subject: "Chemistry", topic: "Organic Chemistry", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "Which of the following is the most stable carbocation?", options: { A: "CH₃⁺ (methyl)", B: "(CH₃)₂CH⁺ (secondary)", C: "(CH₃)₃C⁺ (tertiary)", D: "C₂H₅⁺ (ethyl)" }, correctAnswer: "C", solution: "Carbocation stability increases with the number of alkyl groups attached: tertiary > secondary > primary > methyl. The tertiary carbocation (CH₃)₃C⁺ is the most stable due to hyperconjugation and inductive effects.", marks: 4 },
  { subject: "Chemistry", topic: "Organic Chemistry", classGrade: "12", year: 2022, difficulty: "hard", questionType: "mcq", questionText: "Markovnikov's rule applies to the addition of HBr to:", options: { A: "Ethene", B: "Propene", C: "Ethyne", D: "Benzene" }, correctAnswer: "B", solution: "Markovnikov's rule states that in addition of HX to an unsymmetrical alkene, H adds to the carbon with more hydrogen atoms. This is meaningful only for unsymmetrical alkenes like propene (CH₃CH=CH₂). Ethene is symmetrical, so the rule doesn't distinguish products.", marks: 4 },
  { subject: "Chemistry", topic: "Organic Chemistry", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "The reagent used to distinguish between a primary, secondary, and tertiary alcohol is:", options: { A: "Sodium metal", B: "Lucas reagent (ZnCl₂/HCl)", C: "Tollens reagent", D: "Fehling solution" }, correctAnswer: "B", solution: "Lucas reagent (anhydrous ZnCl₂ + conc. HCl) distinguishes alcohols: tertiary gives immediate turbidity, secondary gives turbidity in 5 minutes, primary gives no turbidity at room temperature.", marks: 4 },
  { subject: "Chemistry", topic: "Electrochemistry", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "In an electrochemical cell, oxidation takes place at the:", options: { A: "Cathode", B: "Anode", C: "Salt bridge", D: "External circuit" }, correctAnswer: "B", solution: "In any electrochemical cell, oxidation (loss of electrons) occurs at the anode, and reduction (gain of electrons) occurs at the cathode. Remember: An Ox, Red Cat.", marks: 4 },
  { subject: "Chemistry", topic: "Electrochemistry", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "The standard electrode potential of Cu²⁺/Cu is +0.34 V and that of Zn²⁺/Zn is -0.76 V. The EMF of the Daniell cell is:", options: { A: "0.42 V", B: "1.10 V", C: "0.76 V", D: "0.34 V" }, correctAnswer: "B", solution: "EMF = E°(cathode) - E°(anode) = E°(Cu²⁺/Cu) - E°(Zn²⁺/Zn) = 0.34 - (-0.76) = 0.34 + 0.76 = 1.10 V.", marks: 4 },
  { subject: "Chemistry", topic: "Electrochemistry", classGrade: "12", year: 2023, difficulty: "hard", questionType: "mcq", questionText: "During electrolysis of molten NaCl, the product obtained at the cathode is:", options: { A: "Chlorine gas", B: "Sodium metal", C: "Sodium hydroxide", D: "Hydrogen gas" }, correctAnswer: "B", solution: "At the cathode, reduction occurs: Na⁺ + e⁻ → Na (sodium metal). At the anode, oxidation occurs: 2Cl⁻ → Cl₂ + 2e⁻ (chlorine gas).", marks: 4 },
  { subject: "Chemistry", topic: "Chemical Kinetics", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The unit of rate constant for a first-order reaction is:", options: { A: "mol L⁻¹ s⁻¹", B: "s⁻¹", C: "L mol⁻¹ s⁻¹", D: "L² mol⁻² s⁻¹" }, correctAnswer: "B", solution: "For a first-order reaction, rate = k[A]. Units of k = rate/[A] = (mol L⁻¹ s⁻¹)/(mol L⁻¹) = s⁻¹.", marks: 4 },
  { subject: "Chemistry", topic: "Chemical Kinetics", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "The half-life of a first-order reaction with rate constant k = 0.0693 s⁻¹ is:", options: { A: "5 s", B: "10 s", C: "15 s", D: "20 s" }, correctAnswer: "B", solution: "For first-order: t₁/₂ = 0.693/k = 0.693/0.0693 = 10 s.", marks: 4 },
  { subject: "Chemistry", topic: "Solutions", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "Molarity is defined as the number of moles of solute per:", options: { A: "Kilogram of solvent", B: "Litre of solution", C: "Litre of solvent", D: "Kilogram of solution" }, correctAnswer: "B", solution: "Molarity (M) = number of moles of solute / volume of solution in litres.", marks: 4 },
  { subject: "Chemistry", topic: "Solutions", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "The elevation in boiling point is a colligative property because it depends on:", options: { A: "Nature of solute", B: "Nature of solvent", C: "Number of solute particles", D: "Size of solute particles" }, correctAnswer: "C", solution: "Colligative properties depend only on the number (concentration) of solute particles, not on their nature. Elevation in boiling point ΔTb = Kb × m, where m is molality.", marks: 4 },
  { subject: "Chemistry", topic: "Coordination Compounds", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "The coordination number of cobalt in [Co(NH₃)₆]³⁺ is:", options: { A: "3", B: "4", C: "6", D: "8" }, correctAnswer: "C", solution: "The coordination number is the number of ligand donor atoms directly bonded to the central metal ion. In [Co(NH₃)₆]³⁺, six NH₃ molecules are coordinated to Co³⁺, giving a coordination number of 6.", marks: 4 },
  { subject: "Chemistry", topic: "Coordination Compounds", classGrade: "12", year: 2021, difficulty: "hard", questionType: "mcq", questionText: "The hybridisation of Ni in [Ni(CN)₄]²⁻ is:", options: { A: "sp³", B: "dsp²", C: "sp³d", D: "d²sp³" }, correctAnswer: "B", solution: "CN⁻ is a strong field ligand causing pairing. Ni²⁺ (3d⁸) pairs up to give one empty 3d orbital. It undergoes dsp² hybridisation forming a square planar complex.", marks: 4 },
  { subject: "Chemistry", topic: "Surface Chemistry", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The Tyndall effect is observed in:", options: { A: "True solutions", B: "Colloidal solutions", C: "Suspensions", D: "Both B and C" }, correctAnswer: "B", solution: "The Tyndall effect (scattering of light by colloidal particles) is characteristic of colloidal solutions. True solutions don't show it (particles too small), and suspensions settle down.", marks: 4 },
  { subject: "Chemistry", topic: "Surface Chemistry", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "Physical adsorption is characterised by:", options: { A: "High activation energy", B: "Irreversibility", C: "Low enthalpy of adsorption", D: "Chemical bond formation" }, correctAnswer: "C", solution: "Physical adsorption (physisorption) involves weak van der Waals forces, has low enthalpy of adsorption (20-40 kJ/mol), is reversible, and decreases with increasing temperature.", marks: 4 },
  { subject: "Chemistry", topic: "Inorganic Chemistry", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The most abundant element in Earth's crust is:", options: { A: "Silicon", B: "Aluminium", C: "Oxygen", D: "Iron" }, correctAnswer: "C", solution: "Oxygen is the most abundant element in Earth's crust, making up about 46% by mass. Silicon is second at about 28%.", marks: 4 },
  { subject: "Chemistry", topic: "Inorganic Chemistry", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "Which of the following is an example of a Lewis acid?", options: { A: "NH₃", B: "BF₃", C: "NaOH", D: "H₂O" }, correctAnswer: "B", solution: "A Lewis acid is an electron pair acceptor. BF₃ has an empty p-orbital on boron and can accept an electron pair, making it a strong Lewis acid.", marks: 4 },
  { subject: "Chemistry", topic: "Physical Chemistry", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "For an ideal gas, the compressibility factor Z is:", options: { A: "Greater than 1", B: "Less than 1", C: "Equal to 1", D: "Variable" }, correctAnswer: "C", solution: "The compressibility factor Z = PV/nRT. For an ideal gas, PV = nRT, so Z = 1 exactly. Deviations from Z = 1 indicate non-ideal behaviour.", marks: 4 },
  { subject: "Chemistry", topic: "States of Matter", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "At constant temperature, the volume of a gas is inversely proportional to pressure. This is:", options: { A: "Charles's law", B: "Boyle's law", C: "Gay-Lussac's law", D: "Avogadro's law" }, correctAnswer: "B", solution: "Boyle's law states that at constant temperature, the volume of a fixed amount of gas is inversely proportional to its pressure: PV = constant.", marks: 4 },
  { subject: "Chemistry", topic: "States of Matter", classGrade: "11", year: 2022, difficulty: "medium", questionType: "mcq", questionText: "The root mean square speed of gas molecules is proportional to:", options: { A: "√T", B: "T", C: "T²", D: "1/T" }, correctAnswer: "A", solution: "The RMS speed vrms = √(3RT/M). It is proportional to the square root of absolute temperature (√T).", marks: 4 },
  { subject: "Chemistry", topic: "Redox Reactions", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "In the reaction 2Mg + O₂ → 2MgO, magnesium is:", options: { A: "Reduced", B: "Oxidised", C: "Neither oxidised nor reduced", D: "Both oxidised and reduced" }, correctAnswer: "B", solution: "Magnesium goes from 0 oxidation state to +2 in MgO, losing electrons. Loss of electrons is oxidation, so Mg is oxidised.", marks: 4 },
  { subject: "Chemistry", topic: "Polymers", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The monomer of polythene (polyethylene) is:", options: { A: "Propylene", B: "Ethylene", C: "Styrene", D: "Vinyl chloride" }, correctAnswer: "B", solution: "Polythene (polyethylene) is formed by the addition polymerisation of ethylene (ethene, CH₂=CH₂) monomers.", marks: 4 },
  { subject: "Chemistry", topic: "Biomolecules", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "Sucrose is a disaccharide composed of:", options: { A: "Glucose + Glucose", B: "Glucose + Fructose", C: "Glucose + Galactose", D: "Fructose + Fructose" }, correctAnswer: "B", solution: "Sucrose (table sugar) is a disaccharide formed by the condensation of one molecule of glucose and one molecule of fructose linked by a glycosidic bond.", marks: 4 },
  { subject: "Chemistry", topic: "Biomolecules", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "The secondary structure of proteins is stabilised by:", options: { A: "Peptide bonds", B: "Hydrogen bonds", C: "Disulphide bonds", D: "Ionic bonds" }, correctAnswer: "B", solution: "The secondary structure of proteins (α-helix and β-pleated sheet) is stabilised by hydrogen bonds between the C=O and N-H groups of the polypeptide backbone.", marks: 4 },
  { subject: "Chemistry", topic: "Environmental Chemistry", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "Ozone depletion in the stratosphere is primarily caused by:", options: { A: "Carbon dioxide", B: "Chlorofluorocarbons (CFCs)", C: "Methane", D: "Nitrogen oxides" }, correctAnswer: "B", solution: "CFCs release chlorine atoms in the stratosphere under UV radiation. Each chlorine atom can destroy thousands of ozone molecules through a catalytic cycle.", marks: 4 },
  { subject: "Chemistry", topic: "Solid State", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "The number of atoms per unit cell in a face-centred cubic (FCC) structure is:", options: { A: "1", B: "2", C: "4", D: "8" }, correctAnswer: "C", solution: "In FCC: 8 corner atoms × 1/8 = 1, plus 6 face-centred atoms × 1/2 = 3. Total = 1 + 3 = 4 atoms per unit cell.", marks: 4 },
  { subject: "Chemistry", topic: "Solid State", classGrade: "12", year: 2023, difficulty: "hard", questionType: "mcq", questionText: "The packing efficiency of a body-centred cubic (BCC) structure is approximately:", options: { A: "52%", B: "68%", C: "74%", D: "90%" }, correctAnswer: "B", solution: "For BCC: packing efficiency = (2 × 4/3 × π × r³) / a³ × 100, where a = 4r/√3. This gives approximately 68%.", marks: 4 },
  { subject: "Chemistry", topic: "Organic Chemistry", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "The number of structural isomers of butane (C₄H₁₀) is:", options: { A: "1", B: "2", C: "3", D: "4" }, correctAnswer: "B", solution: "Butane has 2 structural isomers: n-butane and isobutane (2-methylpropane).", marks: 4 },
  { subject: "Chemistry", topic: "Organic Chemistry", classGrade: "12", year: 2023, difficulty: "hard", questionType: "mcq", questionText: "The product of Wurtz reaction of chloroethane is:", options: { A: "Ethane", B: "Butane", C: "Propane", D: "Hexane" }, correctAnswer: "B", solution: "Wurtz reaction: 2CH₃CH₂Cl + 2Na → CH₃CH₂CH₂CH₃ (butane) + 2NaCl.", marks: 4 },
  { subject: "Chemistry", topic: "Physical Chemistry", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "The number of moles of CO₂ in 44 g of CO₂ is:", options: { A: "0.5", B: "1", C: "2", D: "4.4" }, correctAnswer: "B", solution: "Molar mass of CO₂ = 44 g/mol. Moles = 44/44 = 1.", marks: 4 },
  { subject: "Chemistry", topic: "Inorganic Chemistry", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The ore of aluminium is:", options: { A: "Haematite", B: "Bauxite", C: "Galena", D: "Chalcopyrite" }, correctAnswer: "B", solution: "Bauxite (Al₂O₃·2H₂O) is the principal ore of aluminium.", marks: 4 },
  { subject: "Chemistry", topic: "Chemical Bonding", classGrade: "11", year: null, difficulty: "hard", questionType: "mcq", questionText: "The hybridisation of carbon in diamond is:", options: { A: "sp", B: "sp²", C: "sp³", D: "sp³d" }, correctAnswer: "C", solution: "In diamond, each carbon is sp³ hybridised, forming 4 sigma bonds in a tetrahedral arrangement.", marks: 4 },
  { subject: "Chemistry", topic: "Thermodynamics", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "For a spontaneous process at constant temperature and pressure:", options: { A: "ΔG > 0", B: "ΔG = 0", C: "ΔG < 0", D: "ΔH > 0" }, correctAnswer: "C", solution: "A spontaneous process at constant T and P has ΔG < 0. ΔG = ΔH - TΔS.", marks: 4 },
  { subject: "Chemistry", topic: "Organic Chemistry", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The functional group present in aldehydes is:", options: { A: "-OH", B: "-COOH", C: "-CHO", D: "-CO-" }, correctAnswer: "C", solution: "Aldehydes contain the -CHO group — a carbonyl (C=O) bonded to at least one hydrogen.", marks: 4 },
  { subject: "Chemistry", topic: "Analytical Chemistry", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "Chromatography is used to:", options: { A: "Measure temperature", B: "Separate mixtures", C: "Determine molecular weight", D: "Measure pH" }, correctAnswer: "B", solution: "Chromatography separates mixture components based on different migration rates through a stationary phase.", marks: 4 },
];

const mathematics: SeedQuestion[] = [
  { subject: "Mathematics", topic: "Algebra", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The sum of the roots of the quadratic equation x² - 5x + 6 = 0 is:", options: { A: "5", B: "6", C: "-5", D: "-6" }, correctAnswer: "A", solution: "For ax² + bx + c = 0, sum of roots = -b/a = -(-5)/1 = 5.", marks: 4 },
  { subject: "Mathematics", topic: "Algebra", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "If log₁₀(x) = 3, then x equals:", options: { A: "30", B: "100", C: "1000", D: "10000" }, correctAnswer: "C", solution: "log₁₀(x) = 3 means 10³ = x. Therefore x = 1000.", marks: 4 },
  { subject: "Mathematics", topic: "Algebra", classGrade: "11", year: 2022, difficulty: "medium", questionType: "mcq", questionText: "The value of ⁿC₀ + ⁿC₁ + ⁿC₂ + ... + ⁿCₙ is:", options: { A: "n!", B: "2ⁿ", C: "2ⁿ⁻¹", D: "n²" }, correctAnswer: "B", solution: "By the binomial theorem, (1 + 1)ⁿ = ⁿC₀ + ⁿC₁ + ⁿC₂ + ... + ⁿCₙ = 2ⁿ.", marks: 4 },
  { subject: "Mathematics", topic: "Algebra", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "The number of ways to arrange the letters of the word 'BOOK' is:", options: { A: "12", B: "24", C: "6", D: "4" }, correctAnswer: "A", solution: "BOOK has 4 letters with O repeated twice. Number of arrangements = 4!/2! = 24/2 = 12.", marks: 4 },
  { subject: "Mathematics", topic: "Algebra", classGrade: "11", year: null, difficulty: "hard", questionType: "mcq", questionText: "If α and β are roots of x² - 3x + 1 = 0, then α² + β² equals:", options: { A: "5", B: "7", C: "9", D: "11" }, correctAnswer: "B", solution: "α + β = 3 (sum of roots), αβ = 1 (product of roots). α² + β² = (α + β)² - 2αβ = 9 - 2 = 7.", marks: 4 },
  { subject: "Mathematics", topic: "Calculus", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The derivative of sin(x) with respect to x is:", options: { A: "-sin(x)", B: "cos(x)", C: "-cos(x)", D: "tan(x)" }, correctAnswer: "B", solution: "d/dx[sin(x)] = cos(x). This is a fundamental derivative result.", marks: 4 },
  { subject: "Mathematics", topic: "Calculus", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "∫ 2x dx equals:", options: { A: "x² + C", B: "2x² + C", C: "x + C", D: "x²/2 + C" }, correctAnswer: "A", solution: "∫ 2x dx = 2 × x²/2 + C = x² + C.", marks: 4 },
  { subject: "Mathematics", topic: "Calculus", classGrade: "12", year: 2023, difficulty: "medium", questionType: "mcq", questionText: "The value of ∫₀¹ x² dx is:", options: { A: "1/4", B: "1/3", C: "1/2", D: "1" }, correctAnswer: "B", solution: "∫₀¹ x² dx = [x³/3]₀¹ = 1/3 - 0 = 1/3.", marks: 4 },
  { subject: "Mathematics", topic: "Calculus", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "If f(x) = eˣ sin(x), then f'(x) equals:", options: { A: "eˣ sin(x)", B: "eˣ cos(x)", C: "eˣ(sin(x) + cos(x))", D: "eˣ(sin(x) - cos(x))" }, correctAnswer: "C", solution: "Using product rule: f'(x) = eˣ sin(x) + eˣ cos(x) = eˣ(sin(x) + cos(x)).", marks: 4 },
  { subject: "Mathematics", topic: "Calculus", classGrade: "12", year: null, difficulty: "hard", questionType: "mcq", questionText: "The function f(x) = x³ - 3x + 2 has a local maximum at:", options: { A: "x = 0", B: "x = 1", C: "x = -1", D: "x = 2" }, correctAnswer: "C", solution: "f'(x) = 3x² - 3 = 0 gives x = ±1. f''(x) = 6x. At x = -1: f''(-1) = -6 < 0, so x = -1 is a local maximum. At x = 1: f''(1) = 6 > 0, so local minimum.", marks: 4 },
  { subject: "Mathematics", topic: "Coordinate Geometry", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The distance between the points (1, 2) and (4, 6) is:", options: { A: "3", B: "4", C: "5", D: "7" }, correctAnswer: "C", solution: "Distance = √[(4-1)² + (6-2)²] = √[9 + 16] = √25 = 5.", marks: 4 },
  { subject: "Mathematics", topic: "Coordinate Geometry", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "The equation of a circle with centre (2, 3) and radius 5 is:", options: { A: "(x-2)² + (y-3)² = 5", B: "(x-2)² + (y-3)² = 25", C: "(x+2)² + (y+3)² = 25", D: "x² + y² = 25" }, correctAnswer: "B", solution: "The standard equation of a circle with centre (h, k) and radius r is (x-h)² + (y-k)² = r². Here (x-2)² + (y-3)² = 25.", marks: 4 },
  { subject: "Mathematics", topic: "Coordinate Geometry", classGrade: "12", year: 2022, difficulty: "hard", questionType: "mcq", questionText: "The eccentricity of the ellipse x²/16 + y²/9 = 1 is:", options: { A: "√7/4", B: "√7/3", C: "3/4", D: "7/16" }, correctAnswer: "A", solution: "For ellipse x²/a² + y²/b² = 1 with a > b: e = √(1 - b²/a²) = √(1 - 9/16) = √(7/16) = √7/4.", marks: 4 },
  { subject: "Mathematics", topic: "Trigonometry", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The value of sin(30°) is:", options: { A: "0", B: "1/2", C: "√3/2", D: "1" }, correctAnswer: "B", solution: "sin(30°) = 1/2. This is a standard trigonometric value.", marks: 4 },
  { subject: "Mathematics", topic: "Trigonometry", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "If sin(A) = 3/5, where A is in the first quadrant, then cos(A) equals:", options: { A: "4/5", B: "3/5", C: "5/4", D: "5/3" }, correctAnswer: "A", solution: "Using sin²A + cos²A = 1: cos²A = 1 - 9/25 = 16/25. Since A is in first quadrant, cosA = 4/5.", marks: 4 },
  { subject: "Mathematics", topic: "Trigonometry", classGrade: "11", year: null, difficulty: "hard", questionType: "mcq", questionText: "The general solution of sin(x) = 1/2 is:", options: { A: "x = nπ + (-1)ⁿ(π/6), n ∈ Z", B: "x = 2nπ + π/6, n ∈ Z", C: "x = nπ + π/6, n ∈ Z", D: "x = 2nπ ± π/6, n ∈ Z" }, correctAnswer: "A", solution: "The general solution of sin(x) = sin(α) is x = nπ + (-1)ⁿα. Here α = π/6, so x = nπ + (-1)ⁿ(π/6), where n ∈ Z.", marks: 4 },
  { subject: "Mathematics", topic: "Probability", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "A coin is tossed twice. The probability of getting at least one head is:", options: { A: "1/4", B: "1/2", C: "3/4", D: "1" }, correctAnswer: "C", solution: "P(at least one head) = 1 - P(no head) = 1 - P(TT) = 1 - 1/4 = 3/4.", marks: 4 },
  { subject: "Mathematics", topic: "Probability", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "If P(A) = 0.3, P(B) = 0.4, and P(A ∩ B) = 0.12, then A and B are:", options: { A: "Mutually exclusive", B: "Independent", C: "Dependent", D: "Complementary" }, correctAnswer: "B", solution: "Two events are independent if P(A ∩ B) = P(A) × P(B). Here P(A) × P(B) = 0.3 × 0.4 = 0.12 = P(A ∩ B). So A and B are independent.", marks: 4 },
  { subject: "Mathematics", topic: "Probability", classGrade: "12", year: 2021, difficulty: "hard", questionType: "mcq", questionText: "A bag contains 5 red and 3 blue balls. Two balls are drawn without replacement. The probability that both are red is:", options: { A: "5/14", B: "10/28", C: "25/64", D: "5/8" }, correctAnswer: "B", solution: "P(both red) = (5/8) × (4/7) = 20/56 = 10/28 = 5/14. Options A and B are equivalent fractions, so the answer is B (10/28 = 5/14).", marks: 4 },
  { subject: "Mathematics", topic: "Vectors", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The magnitude of vector 3î + 4ĵ is:", options: { A: "3", B: "4", C: "5", D: "7" }, correctAnswer: "C", solution: "|3î + 4ĵ| = √(3² + 4²) = √(9 + 16) = √25 = 5.", marks: 4 },
  { subject: "Mathematics", topic: "Vectors", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "The dot product of vectors a = 2î + 3ĵ and b = 4î - ĵ is:", options: { A: "5", B: "11", C: "8", D: "-5" }, correctAnswer: "A", solution: "a · b = (2)(4) + (3)(-1) = 8 - 3 = 5.", marks: 4 },
  { subject: "Mathematics", topic: "Vectors", classGrade: "12", year: null, difficulty: "hard", questionType: "mcq", questionText: "If |a × b| = |a · b|, then the angle between vectors a and b is:", options: { A: "0°", B: "30°", C: "45°", D: "90°" }, correctAnswer: "C", solution: "|a × b| = |a||b|sinθ and |a · b| = |a||b|cosθ. Setting equal: sinθ = cosθ, so tanθ = 1, giving θ = 45°.", marks: 4 },
  { subject: "Mathematics", topic: "Matrices", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The determinant of a 2×2 identity matrix is:", options: { A: "0", B: "1", C: "2", D: "-1" }, correctAnswer: "B", solution: "The 2×2 identity matrix is [[1,0],[0,1]]. Its determinant = (1)(1) - (0)(0) = 1.", marks: 4 },
  { subject: "Mathematics", topic: "Matrices", classGrade: "12", year: 2023, difficulty: "medium", questionType: "mcq", questionText: "If A = [[2, 1], [3, 4]], then the determinant of A is:", options: { A: "5", B: "8", C: "11", D: "-5" }, correctAnswer: "A", solution: "det(A) = (2)(4) - (1)(3) = 8 - 3 = 5.", marks: 4 },
  { subject: "Mathematics", topic: "Matrices", classGrade: "12", year: null, difficulty: "hard", questionType: "mcq", questionText: "A square matrix A is said to be singular if:", options: { A: "det(A) = 1", B: "det(A) = 0", C: "A = Aᵀ", D: "A = A⁻¹" }, correctAnswer: "B", solution: "A square matrix is singular (non-invertible) when its determinant equals zero. It means the matrix does not have an inverse.", marks: 4 },
  { subject: "Mathematics", topic: "Sequences and Series", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The sum of the first 10 natural numbers is:", options: { A: "45", B: "55", C: "65", D: "100" }, correctAnswer: "B", solution: "Sum = n(n+1)/2 = 10(11)/2 = 55.", marks: 4 },
  { subject: "Mathematics", topic: "Sequences and Series", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "The sum of an infinite geometric series with first term 4 and common ratio 1/2 is:", options: { A: "4", B: "6", C: "8", D: "16" }, correctAnswer: "C", solution: "For |r| < 1, S∞ = a/(1-r) = 4/(1 - 1/2) = 4/(1/2) = 8.", marks: 4 },
  { subject: "Mathematics", topic: "Sequences and Series", classGrade: "11", year: 2022, difficulty: "hard", questionType: "mcq", questionText: "The nth term of the series 2, 5, 10, 17, 26, ... is:", options: { A: "n² + 1", B: "2n + 1", C: "n² - 1", D: "3n - 1" }, correctAnswer: "A", solution: "For n=1: 1²+1=2, n=2: 4+1=5, n=3: 9+1=10, n=4: 16+1=17, n=5: 25+1=26. The pattern is n² + 1.", marks: 4 },
  { subject: "Mathematics", topic: "Sets and Relations", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "If A = {1, 2, 3} and B = {2, 3, 4}, then A ∩ B is:", options: { A: "{1, 2, 3, 4}", B: "{2, 3}", C: "{1, 4}", D: "{}" }, correctAnswer: "B", solution: "A ∩ B is the intersection — elements common to both A and B = {2, 3}.", marks: 4 },
  { subject: "Mathematics", topic: "Complex Numbers", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "The modulus of the complex number 3 + 4i is:", options: { A: "3", B: "4", C: "5", D: "7" }, correctAnswer: "C", solution: "|3 + 4i| = √(3² + 4²) = √(9 + 16) = √25 = 5.", marks: 4 },
  { subject: "Mathematics", topic: "Complex Numbers", classGrade: "11", year: null, difficulty: "hard", questionType: "mcq", questionText: "The value of i⁴⁵ is:", options: { A: "1", B: "-1", C: "i", D: "-i" }, correctAnswer: "C", solution: "Powers of i cycle with period 4: i¹=i, i²=-1, i³=-i, i⁴=1. 45 = 4×11 + 1, so i⁴⁵ = i¹ = i.", marks: 4 },
  { subject: "Mathematics", topic: "Linear Programming", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "In linear programming, the objective function is:", options: { A: "Always quadratic", B: "A linear function to be optimised", C: "A constraint", D: "Always equal to zero" }, correctAnswer: "B", solution: "The objective function in linear programming is a linear function of the decision variables that needs to be maximised or minimised subject to the given constraints.", marks: 4 },
  { subject: "Mathematics", topic: "Differential Equations", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "The order of the differential equation d²y/dx² + 3(dy/dx) + 2y = 0 is:", options: { A: "1", B: "2", C: "3", D: "0" }, correctAnswer: "B", solution: "The order of a differential equation is the highest order derivative present. Here d²y/dx² is the highest derivative, which is of order 2.", marks: 4 },
  { subject: "Mathematics", topic: "Differential Equations", classGrade: "12", year: 2021, difficulty: "hard", questionType: "mcq", questionText: "The integrating factor of the differential equation dy/dx + y/x = x² is:", options: { A: "x", B: "1/x", C: "eˣ", D: "log x" }, correctAnswer: "A", solution: "For dy/dx + Py = Q, integrating factor = e^(∫P dx). Here P = 1/x, so IF = e^(∫1/x dx) = e^(ln x) = x.", marks: 4 },
  { subject: "Mathematics", topic: "Statistics", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The mean of the data set {2, 4, 6, 8, 10} is:", options: { A: "5", B: "6", C: "7", D: "8" }, correctAnswer: "B", solution: "Mean = (2 + 4 + 6 + 8 + 10)/5 = 30/5 = 6.", marks: 4 },
  { subject: "Mathematics", topic: "Statistics", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "The variance of the data set {1, 2, 3, 4, 5} is:", options: { A: "1", B: "2", C: "3", D: "4" }, correctAnswer: "B", solution: "Mean = 3. Variance = [(1-3)² + (2-3)² + (3-3)² + (4-3)² + (5-3)²]/5 = [4+1+0+1+4]/5 = 10/5 = 2.", marks: 4 },
  { subject: "Mathematics", topic: "Relations and Functions", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "A function f: A → B is bijective if it is:", options: { A: "One-one only", B: "Onto only", C: "Both one-one and onto", D: "Neither one-one nor onto" }, correctAnswer: "C", solution: "A function is bijective if it is both injective (one-one) and surjective (onto). This means every element in B has exactly one pre-image in A.", marks: 4 },
  { subject: "Mathematics", topic: "Three-Dimensional Geometry", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "The distance of the point (1, 2, 3) from the origin is:", options: { A: "√6", B: "√14", C: "6", D: "14" }, correctAnswer: "B", solution: "Distance = √(1² + 2² + 3²) = √(1 + 4 + 9) = √14.", marks: 4 },
  { subject: "Mathematics", topic: "Limits and Continuity", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "The value of lim(x→0) sin(x)/x is:", options: { A: "0", B: "1", C: "∞", D: "Does not exist" }, correctAnswer: "B", solution: "This is a fundamental limit in calculus: lim(x→0) sin(x)/x = 1. It can be proved using the squeeze theorem.", marks: 4 },
  { subject: "Mathematics", topic: "Mathematical Reasoning", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The contrapositive of 'If p then q' is:", options: { A: "If q then p", B: "If not-p then not-q", C: "If not-q then not-p", D: "If p then not-q" }, correctAnswer: "C", solution: "The contrapositive of p → q is ¬q → ¬p. The contrapositive is logically equivalent to the original statement.", marks: 4 },
  { subject: "Mathematics", topic: "Calculus", classGrade: "12", year: null, difficulty: "hard", questionType: "mcq", questionText: "The area bounded by the curve y = x², the x-axis, and the lines x = 0 and x = 2 is:", options: { A: "4/3", B: "8/3", C: "4", D: "2/3" }, correctAnswer: "B", solution: "Area = ∫₀² x² dx = [x³/3]₀² = 8/3 square units.", marks: 4 },
  { subject: "Mathematics", topic: "Trigonometry", classGrade: "11", year: 2023, difficulty: "medium", questionType: "mcq", questionText: "The value of cos²(45°) + sin²(45°) is:", options: { A: "0", B: "1/2", C: "1", D: "2" }, correctAnswer: "C", solution: "Pythagorean identity: sin²θ + cos²θ = 1 for all θ.", marks: 4 },
  { subject: "Mathematics", topic: "Coordinate Geometry", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The slope of the line 2x + 3y = 6 is:", options: { A: "2/3", B: "-2/3", C: "3/2", D: "-3/2" }, correctAnswer: "B", solution: "Rewriting: y = (-2/3)x + 2. Slope m = -2/3.", marks: 4 },
  { subject: "Mathematics", topic: "Sets and Relations", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "The number of subsets of a set containing 4 elements is:", options: { A: "4", B: "8", C: "16", D: "32" }, correctAnswer: "C", solution: "A set with n elements has 2ⁿ subsets. For n = 4: 2⁴ = 16.", marks: 4 },
  { subject: "Mathematics", topic: "Permutations", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "The value of 10! / (8! × 2!) is:", options: { A: "45", B: "90", C: "180", D: "720" }, correctAnswer: "A", solution: "10!/(8! × 2!) = (10 × 9)/(2 × 1) = 45. This is ¹⁰C₂.", marks: 4 },
  { subject: "Mathematics", topic: "Inverse Trigonometric Functions", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "The value of sin⁻¹(1) is:", options: { A: "0", B: "π/6", C: "π/4", D: "π/2" }, correctAnswer: "D", solution: "sin⁻¹(1) = π/2 because sin(π/2) = 1.", marks: 4 },
  { subject: "Mathematics", topic: "Application of Derivatives", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "The rate of change of the area of a circle with respect to its radius r is:", options: { A: "πr", B: "2πr", C: "πr²", D: "4πr" }, correctAnswer: "B", solution: "A = πr². dA/dr = 2πr, which equals the circumference.", marks: 4 },
];

const biology: SeedQuestion[] = [
  { subject: "Biology", topic: "Cell Biology", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The powerhouse of the cell is:", options: { A: "Nucleus", B: "Ribosome", C: "Mitochondria", D: "Golgi apparatus" }, correctAnswer: "C", solution: "Mitochondria are called the powerhouse of the cell because they produce ATP (adenosine triphosphate) through cellular respiration, providing energy for cellular activities.", marks: 4 },
  { subject: "Biology", topic: "Cell Biology", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "Which organelle is responsible for protein synthesis?", options: { A: "Mitochondria", B: "Ribosomes", C: "Lysosomes", D: "Endoplasmic reticulum" }, correctAnswer: "B", solution: "Ribosomes are the sites of protein synthesis. They translate mRNA into amino acid sequences to build proteins. They are found free in cytoplasm or attached to rough endoplasmic reticulum.", marks: 4 },
  { subject: "Biology", topic: "Cell Biology", classGrade: "11", year: 2022, difficulty: "medium", questionType: "mcq", questionText: "The cell membrane is primarily composed of:", options: { A: "Carbohydrates and proteins", B: "Phospholipids and proteins", C: "Nucleic acids and lipids", D: "Proteins and nucleic acids" }, correctAnswer: "B", solution: "The cell membrane follows the fluid mosaic model — a phospholipid bilayer with embedded proteins (integral and peripheral), along with cholesterol and glycolipids.", marks: 4 },
  { subject: "Biology", topic: "Cell Biology", classGrade: "11", year: null, difficulty: "hard", questionType: "mcq", questionText: "During mitosis, chromosomes are most clearly visible during which phase?", options: { A: "Interphase", B: "Prophase", C: "Metaphase", D: "Telophase" }, correctAnswer: "C", solution: "During metaphase, chromosomes are maximally condensed and align at the metaphase plate (equatorial plate), making them most clearly visible under a microscope.", marks: 4 },
  { subject: "Biology", topic: "Genetics", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The basic unit of heredity is:", options: { A: "Chromosome", B: "Gene", C: "DNA", D: "Protein" }, correctAnswer: "B", solution: "A gene is the basic unit of heredity. It is a segment of DNA that contains the instructions for making a specific protein or functional RNA molecule.", marks: 4 },
  { subject: "Biology", topic: "Genetics", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "In Mendel's monohybrid cross, the phenotypic ratio in F₂ generation is:", options: { A: "1:1", B: "1:2:1", C: "3:1", D: "9:3:3:1" }, correctAnswer: "C", solution: "In a monohybrid cross (Tt × Tt), the F₂ generation shows a phenotypic ratio of 3:1 (3 dominant : 1 recessive). The genotypic ratio is 1:2:1 (TT:Tt:tt).", marks: 4 },
  { subject: "Biology", topic: "Genetics", classGrade: "12", year: 2023, difficulty: "hard", questionType: "mcq", questionText: "A cross between a homozygous tall plant (TT) and a homozygous short plant (tt) produces F₁ which are all tall. If F₁ plants are crossed with short plants (test cross), the expected ratio of tall to short in the offspring is:", options: { A: "3:1", B: "1:1", C: "1:3", D: "All tall" }, correctAnswer: "B", solution: "F₁ genotype is Tt. Test cross: Tt × tt gives Tt and tt in equal numbers. Phenotypic ratio = 1 tall : 1 short = 1:1.", marks: 4 },
  { subject: "Biology", topic: "Genetics", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "Which of the following is an example of a sex-linked disorder?", options: { A: "Sickle cell anaemia", B: "Colour blindness", C: "Thalassemia", D: "Down syndrome" }, correctAnswer: "B", solution: "Colour blindness is an X-linked recessive disorder. The gene for colour vision is located on the X chromosome, making males more commonly affected as they have only one X chromosome.", marks: 4 },
  { subject: "Biology", topic: "Human Physiology", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The largest organ of the human body is:", options: { A: "Liver", B: "Brain", C: "Skin", D: "Lungs" }, correctAnswer: "C", solution: "Skin is the largest organ of the human body, covering approximately 1.5-2 square metres in an adult. It serves as a protective barrier against pathogens, UV radiation, and dehydration.", marks: 4 },
  { subject: "Biology", topic: "Human Physiology", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The normal human body temperature is approximately:", options: { A: "35°C", B: "36°C", C: "37°C", D: "38°C" }, correctAnswer: "C", solution: "Normal human body temperature is approximately 37°C (98.6°F). This is maintained by the thermoregulatory centre in the hypothalamus.", marks: 4 },
  { subject: "Biology", topic: "Human Physiology", classGrade: "11", year: 2021, difficulty: "medium", questionType: "mcq", questionText: "Which blood group is known as the universal donor?", options: { A: "A", B: "B", C: "AB", D: "O" }, correctAnswer: "D", solution: "Blood group O is the universal donor because O-type red blood cells have neither A nor B antigens on their surface, so they don't trigger an immune response in any recipient.", marks: 4 },
  { subject: "Biology", topic: "Human Physiology", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "The functional unit of the kidney is:", options: { A: "Neuron", B: "Nephron", C: "Alveolus", D: "Hepatocyte" }, correctAnswer: "B", solution: "The nephron is the functional unit of the kidney. Each kidney contains about 1 million nephrons that filter blood and produce urine through processes of filtration, reabsorption, and secretion.", marks: 4 },
  { subject: "Biology", topic: "Human Physiology", classGrade: "11", year: null, difficulty: "hard", questionType: "mcq", questionText: "The pacemaker of the heart is the:", options: { A: "AV node", B: "SA node", C: "Bundle of His", D: "Purkinje fibres" }, correctAnswer: "B", solution: "The sinoatrial (SA) node is the natural pacemaker of the heart. Located in the right atrium, it generates electrical impulses at ~72 beats/minute that initiate each cardiac cycle.", marks: 4 },
  { subject: "Biology", topic: "Human Physiology", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "The enzyme pepsin works best in:", options: { A: "Alkaline medium", B: "Neutral medium", C: "Acidic medium", D: "Any medium" }, correctAnswer: "C", solution: "Pepsin is a gastric enzyme that functions optimally in an acidic medium (pH 1.5-2.5). The HCl secreted by gastric glands provides this acidic environment in the stomach.", marks: 4 },
  { subject: "Biology", topic: "Plant Physiology", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The green pigment present in leaves that is essential for photosynthesis is:", options: { A: "Haemoglobin", B: "Chlorophyll", C: "Xanthophyll", D: "Carotene" }, correctAnswer: "B", solution: "Chlorophyll is the green pigment found in chloroplasts that absorbs light energy (primarily red and blue wavelengths) for photosynthesis. It reflects green light, giving plants their green colour.", marks: 4 },
  { subject: "Biology", topic: "Plant Physiology", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "The site of light reactions of photosynthesis is:", options: { A: "Stroma", B: "Thylakoid membrane", C: "Outer membrane", D: "Cytoplasm" }, correctAnswer: "B", solution: "Light reactions (photophosphorylation) occur on the thylakoid membranes of chloroplasts. The pigments, electron transport chain, and ATP synthase are all located here.", marks: 4 },
  { subject: "Biology", topic: "Plant Physiology", classGrade: "11", year: 2022, difficulty: "hard", questionType: "mcq", questionText: "In C4 plants, the primary CO₂ acceptor is:", options: { A: "RuBisCO", B: "Phosphoenolpyruvate (PEP)", C: "Ribulose bisphosphate (RuBP)", D: "Oxaloacetate (OAA)" }, correctAnswer: "B", solution: "In C4 plants, the primary CO₂ acceptor is PEP (phosphoenolpyruvate), which combines with CO₂ in mesophyll cells using the enzyme PEP carboxylase to form a 4-carbon compound (OAA). This is the initial fixation step.", marks: 4 },
  { subject: "Biology", topic: "Plant Physiology", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The process of water absorption by plant roots through osmosis is called:", options: { A: "Transpiration", B: "Absorption", C: "Imbibition", D: "Osmosis" }, correctAnswer: "B", solution: "Water absorption by roots occurs primarily through osmosis — movement of water from higher water potential (soil) to lower water potential (root cells) across the semipermeable membrane.", marks: 4 },
  { subject: "Biology", topic: "Ecology", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The term 'ecosystem' was coined by:", options: { A: "Charles Darwin", B: "Arthur Tansley", C: "Gregor Mendel", D: "Ernst Haeckel" }, correctAnswer: "B", solution: "The term 'ecosystem' was coined by Sir Arthur Tansley in 1935. An ecosystem includes all living organisms (biotic) and non-living components (abiotic) in an area, interacting as a system.", marks: 4 },
  { subject: "Biology", topic: "Ecology", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "In a food chain, the 10% law states that:", options: { A: "Only 10% of organisms survive at each level", B: "Only 10% of energy is transferred to the next trophic level", C: "Only 10% of species are producers", D: "10% of biomass is consumed" }, correctAnswer: "B", solution: "Lindeman's 10% law states that only about 10% of the energy at one trophic level is transferred to the next. The rest is lost as heat through respiration and other metabolic activities.", marks: 4 },
  { subject: "Biology", topic: "Ecology", classGrade: "12", year: 2023, difficulty: "hard", questionType: "mcq", questionText: "The type of ecological pyramid that is always upright is:", options: { A: "Pyramid of numbers", B: "Pyramid of biomass", C: "Pyramid of energy", D: "None — all can be inverted" }, correctAnswer: "C", solution: "The pyramid of energy is always upright because energy decreases at each successive trophic level (second law of thermodynamics). Pyramids of numbers and biomass can be inverted in certain ecosystems.", marks: 4 },
  { subject: "Biology", topic: "Ecology", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "The relationship between a clownfish and a sea anemone is an example of:", options: { A: "Parasitism", B: "Predation", C: "Mutualism", D: "Competition" }, correctAnswer: "C", solution: "Clownfish and sea anemone share mutualism — both benefit. The clownfish gets protection from the anemone's stinging tentacles, while it brings food to the anemone and provides nutrients from its waste.", marks: 4 },
  { subject: "Biology", topic: "Evolution", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The theory of natural selection was proposed by:", options: { A: "Lamarck", B: "Darwin", C: "Mendel", D: "Hugo de Vries" }, correctAnswer: "B", solution: "Charles Darwin proposed the theory of natural selection in his book 'On the Origin of Species' (1859). He explained that organisms with favourable variations survive and reproduce more successfully.", marks: 4 },
  { subject: "Biology", topic: "Evolution", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "Organs that have similar structure but different functions are called:", options: { A: "Analogous organs", B: "Homologous organs", C: "Vestigial organs", D: "Rudimentary organs" }, correctAnswer: "B", solution: "Homologous organs have similar structural origin (same ancestral structure) but may perform different functions. Example: forelimbs of humans, whales, bats — same bone structure, different functions.", marks: 4 },
  { subject: "Biology", topic: "Evolution", classGrade: "12", year: null, difficulty: "hard", questionType: "mcq", questionText: "Hardy-Weinberg equilibrium is disturbed by:", options: { A: "Random mating", B: "Large population size", C: "Natural selection", D: "No mutation" }, correctAnswer: "C", solution: "Hardy-Weinberg equilibrium requires: no mutation, random mating, no natural selection, large population, and no migration. Natural selection disturbs this equilibrium by favouring certain alleles.", marks: 4 },
  { subject: "Biology", topic: "Molecular Biology", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "DNA replication is:", options: { A: "Conservative", B: "Semi-conservative", C: "Dispersive", D: "Non-conservative" }, correctAnswer: "B", solution: "DNA replication is semi-conservative, as demonstrated by Meselson and Stahl's experiment (1958). Each new DNA molecule contains one original (parent) strand and one newly synthesised strand.", marks: 4 },
  { subject: "Biology", topic: "Molecular Biology", classGrade: "12", year: 2021, difficulty: "medium", questionType: "mcq", questionText: "The process of copying genetic information from DNA to mRNA is called:", options: { A: "Translation", B: "Transcription", C: "Replication", D: "Transduction" }, correctAnswer: "B", solution: "Transcription is the process where RNA polymerase reads the template strand of DNA and synthesises a complementary mRNA molecule. It occurs in the nucleus of eukaryotic cells.", marks: 4 },
  { subject: "Biology", topic: "Molecular Biology", classGrade: "12", year: null, difficulty: "hard", questionType: "mcq", questionText: "The number of hydrogen bonds between adenine and thymine in DNA is:", options: { A: "1", B: "2", C: "3", D: "4" }, correctAnswer: "B", solution: "Adenine pairs with Thymine via 2 hydrogen bonds (A=T), while Guanine pairs with Cytosine via 3 hydrogen bonds (G≡C). This is Chargaff's base pairing rule.", marks: 4 },
  { subject: "Biology", topic: "Human Reproduction", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The normal gestation period in humans is approximately:", options: { A: "6 months", B: "7 months", C: "9 months", D: "12 months" }, correctAnswer: "C", solution: "The normal gestation period in humans is approximately 9 months (about 266 days from fertilisation or 280 days from the last menstrual period).", marks: 4 },
  { subject: "Biology", topic: "Human Reproduction", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "Fertilisation in humans normally occurs in the:", options: { A: "Uterus", B: "Ovary", C: "Fallopian tube (ampulla)", D: "Cervix" }, correctAnswer: "C", solution: "Fertilisation normally occurs in the ampulla (widest part) of the fallopian tube (oviduct). The fertilised egg (zygote) then travels to the uterus for implantation.", marks: 4 },
  { subject: "Biology", topic: "Biotechnology", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The enzyme used to cut DNA at specific sites is called:", options: { A: "DNA ligase", B: "DNA polymerase", C: "Restriction endonuclease", D: "Helicase" }, correctAnswer: "C", solution: "Restriction endonucleases (restriction enzymes) are molecular scissors that cut DNA at specific recognition sequences. They are essential tools in recombinant DNA technology.", marks: 4 },
  { subject: "Biology", topic: "Biotechnology", classGrade: "12", year: 2022, difficulty: "medium", questionType: "mcq", questionText: "PCR (Polymerase Chain Reaction) is used to:", options: { A: "Translate proteins", B: "Amplify specific DNA sequences", C: "Sequence amino acids", D: "Destroy viruses" }, correctAnswer: "B", solution: "PCR is a technique to amplify (make millions of copies of) a specific DNA segment in vitro. It uses DNA polymerase, primers, and cycles of denaturation, annealing, and extension.", marks: 4 },
  { subject: "Biology", topic: "Biotechnology", classGrade: "12", year: null, difficulty: "hard", questionType: "mcq", questionText: "The first transgenic crop to be commercially released was:", options: { A: "Bt Cotton", B: "Golden Rice", C: "Flavr Savr Tomato", D: "Bt Brinjal" }, correctAnswer: "C", solution: "The Flavr Savr tomato (1994) was the first commercially grown genetically modified food. It was engineered to delay ripening by suppressing the enzyme polygalacturonase.", marks: 4 },
  { subject: "Biology", topic: "Human Health and Disease", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "Malaria is caused by:", options: { A: "Bacteria", B: "Virus", C: "Protozoan (Plasmodium)", D: "Fungus" }, correctAnswer: "C", solution: "Malaria is caused by protozoan parasites of the genus Plasmodium (P. vivax, P. falciparum, P. malariae, P. ovale). It is transmitted by the bite of infected female Anopheles mosquitoes.", marks: 4 },
  { subject: "Biology", topic: "Human Health and Disease", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "Which type of immunity is provided by vaccination?", options: { A: "Natural active immunity", B: "Artificial active immunity", C: "Natural passive immunity", D: "Artificial passive immunity" }, correctAnswer: "B", solution: "Vaccination provides artificial active immunity. The vaccine contains weakened or inactivated pathogens (or their parts) that stimulate the immune system to produce antibodies and memory cells without causing the disease.", marks: 4 },
  { subject: "Biology", topic: "Biodiversity", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The term 'biodiversity' was popularised by:", options: { A: "Charles Darwin", B: "Edward O. Wilson", C: "Alexander von Humboldt", D: "Robert May" }, correctAnswer: "B", solution: "Edward O. Wilson popularised the term 'biodiversity' through his 1988 publication. He is often called the 'father of biodiversity' for his extensive work on biological diversity.", marks: 4 },
  { subject: "Biology", topic: "Biodiversity", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "An area with high species richness and high degree of endemism is called a:", options: { A: "Biome", B: "Biodiversity hotspot", C: "Biosphere reserve", D: "National park" }, correctAnswer: "B", solution: "A biodiversity hotspot is a region with at least 1,500 species of endemic vascular plants and having lost at least 70% of its original habitat. India has 4 hotspots including the Western Ghats.", marks: 4 },
  { subject: "Biology", topic: "Plant Anatomy", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "The tissue responsible for the transport of water in plants is:", options: { A: "Phloem", B: "Xylem", C: "Parenchyma", D: "Collenchyma" }, correctAnswer: "B", solution: "Xylem is the vascular tissue responsible for the upward transport of water and dissolved minerals from roots to leaves. It consists of tracheids, vessels, fibres, and parenchyma.", marks: 4 },
  { subject: "Biology", topic: "Plant Anatomy", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "Guard cells regulate the opening and closing of:", options: { A: "Lenticels", B: "Stomata", C: "Hydathodes", D: "Plasmodesmata" }, correctAnswer: "B", solution: "Guard cells are specialised epidermal cells that surround stomatal pores. They regulate stomatal opening/closing based on turgor pressure, controlling gas exchange and water loss (transpiration).", marks: 4 },
  { subject: "Biology", topic: "Animal Kingdom", classGrade: "11", year: null, difficulty: "easy", questionType: "mcq", questionText: "Animals that maintain a constant body temperature regardless of the environment are called:", options: { A: "Ectotherms", B: "Endotherms", C: "Poikilotherms", D: "Heterotherms" }, correctAnswer: "B", solution: "Endotherms (warm-blooded animals like mammals and birds) maintain a constant internal body temperature through metabolic heat production, regardless of external temperature.", marks: 4 },
  { subject: "Biology", topic: "Animal Kingdom", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "Which phylum includes organisms with a water vascular system?", options: { A: "Arthropoda", B: "Mollusca", C: "Echinodermata", D: "Annelida" }, correctAnswer: "C", solution: "Echinodermata (starfish, sea urchins, etc.) possess a unique water vascular system used for locomotion, food capture, and respiration. It operates through a network of canals with tube feet.", marks: 4 },
  { subject: "Biology", topic: "Microorganisms", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "The bacterium used in the production of insulin through genetic engineering is:", options: { A: "Lactobacillus", B: "Escherichia coli", C: "Streptococcus", D: "Bacillus subtilis" }, correctAnswer: "B", solution: "E. coli was the first organism used to produce human insulin (Humulin) through recombinant DNA technology. The human insulin gene is inserted into E. coli, which then produces insulin.", marks: 4 },
  { subject: "Biology", topic: "Cell Biology", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "The cell organelle involved in intracellular digestion is:", options: { A: "Ribosome", B: "Lysosome", C: "Centrosome", D: "Nucleolus" }, correctAnswer: "B", solution: "Lysosomes contain hydrolytic enzymes for intracellular digestion. Called suicidal bags of the cell.", marks: 4 },
  { subject: "Biology", topic: "Genetics", classGrade: "12", year: null, difficulty: "hard", questionType: "mcq", questionText: "Crossing over occurs during which stage of meiosis?", options: { A: "Prophase I (pachytene)", B: "Metaphase I", C: "Anaphase I", D: "Prophase II" }, correctAnswer: "A", solution: "Crossing over occurs during pachytene of prophase I in meiosis I, leading to genetic recombination.", marks: 4 },
  { subject: "Biology", topic: "Human Physiology", classGrade: "11", year: null, difficulty: "hard", questionType: "mcq", questionText: "The hormone insulin is secreted by:", options: { A: "Alpha cells of pancreas", B: "Beta cells of pancreas", C: "Delta cells of pancreas", D: "Acinar cells of pancreas" }, correctAnswer: "B", solution: "Insulin is secreted by beta cells of the Islets of Langerhans. It lowers blood glucose levels.", marks: 4 },
  { subject: "Biology", topic: "Ecology", classGrade: "12", year: null, difficulty: "easy", questionType: "mcq", questionText: "The primary producers in most ecosystems are:", options: { A: "Herbivores", B: "Carnivores", C: "Green plants", D: "Decomposers" }, correctAnswer: "C", solution: "Green plants (autotrophs) are the primary producers, converting solar energy into chemical energy through photosynthesis.", marks: 4 },
  { subject: "Biology", topic: "Molecular Biology", classGrade: "12", year: null, difficulty: "medium", questionType: "mcq", questionText: "The start codon in mRNA that initiates translation is:", options: { A: "UAA", B: "UAG", C: "AUG", D: "UGA" }, correctAnswer: "C", solution: "AUG is the universal start codon. It codes for methionine. UAA, UAG, UGA are stop codons.", marks: 4 },
  { subject: "Biology", topic: "Plant Physiology", classGrade: "11", year: null, difficulty: "medium", questionType: "mcq", questionText: "The plant hormone responsible for cell elongation is:", options: { A: "Ethylene", B: "Auxin", C: "Abscisic acid", D: "Cytokinin" }, correctAnswer: "B", solution: "Auxin (IAA) is the primary hormone for cell elongation, phototropism, and gravitropism.", marks: 4 },
  { subject: "Biology", topic: "Genetics", classGrade: "12", year: 2021, difficulty: "medium", questionType: "mcq", questionText: "The law of independent assortment applies to genes located on:", options: { A: "The same chromosome", B: "Different chromosomes", C: "Sex chromosomes only", D: "Mitochondrial DNA" }, correctAnswer: "B", solution: "Independent assortment applies to genes on different chromosomes. Linked genes on the same chromosome do not assort independently.", marks: 4 },
  { subject: "Biology", topic: "Evolution", classGrade: "12", year: null, difficulty: "hard", questionType: "mcq", questionText: "The wings of a bird and the wings of an insect are examples of:", options: { A: "Homologous organs", B: "Analogous organs", C: "Vestigial organs", D: "Atavistic organs" }, correctAnswer: "B", solution: "They are analogous organs — similar function (flight) but different structural origin. This is convergent evolution.", marks: 4 },
  { subject: "Biology", topic: "Human Health and Disease", classGrade: "12", year: null, difficulty: "hard", questionType: "mcq", questionText: "The cells directly involved in killing virus-infected cells are:", options: { A: "B-lymphocytes", B: "Helper T-cells", C: "Cytotoxic T-cells", D: "Macrophages" }, correctAnswer: "C", solution: "Cytotoxic T-cells (CD8+) directly kill virus-infected cells by releasing perforins and granzymes.", marks: 4 },
];

async function seedQuestions() {
  console.log("🔬 Seeding Question Bank...");

  const allQuestions = [...physics, ...chemistry, ...mathematics, ...biology];
  console.log(`  Total questions to seed: ${allQuestions.length}`);
  console.log(`  Physics: ${physics.length}`);
  console.log(`  Chemistry: ${chemistry.length}`);
  console.log(`  Mathematics: ${mathematics.length}`);
  console.log(`  Biology: ${biology.length}`);

  const existing = await pool.query("SELECT COUNT(*)::int as cnt FROM question_bank.question_bank WHERE created_by IS NULL");
  const existingCount = existing.rows[0].cnt;
  if (existingCount > 0) {
    console.log(`  Clearing ${existingCount} existing seed questions (created_by IS NULL)...`);
    await pool.query("DELETE FROM question_bank.question_bank WHERE created_by IS NULL");
  }

  const batchSize = 100;
  let inserted = 0;

  for (let i = 0; i < allQuestions.length; i += batchSize) {
    const batch = allQuestions.slice(i, i + batchSize);
    await db.insert(questionBank).values(
      batch.map((q) => ({
        subject: q.subject,
        topic: q.topic,
        classGrade: q.classGrade,
        year: q.year,
        difficulty: q.difficulty,
        questionType: q.questionType,
        questionText: q.questionText,
        options: q.options,
        correctAnswer: q.correctAnswer,
        solution: q.solution,
        marks: q.marks,
        isPublished: true,
      })),
    );
    inserted += batch.length;
    console.log(`  Inserted ${inserted}/${allQuestions.length}...`);
  }

  console.log(`\n✅ Question Bank seeded with ${inserted} questions!`);
  await pool.end();
}

seedQuestions().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
